title: Teodor Georgiev # your name (or website title) here
logo: "/images/foto.jpg?raw=true" # your photo (or logo) here
#logo: "/images/cv_round.png?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  <br>
  Data Analyst with a master’s degree in Economics & Data Science from Bielefeld University in Germany.
  <br><br>
  <a href="https://www.linkedin.com/in/teodor-georgiev-60a812245/">View my LinkedIn Profile</a> 
  
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here

colors:
  crimson: '#900C3F'
